<project    xmlns="http://maven.apache.org/POM/4.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                                https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.pgdro</groupId>
    <artifactId>utilities</artifactId>
    <version>1.1.0</version>
    <packaging>jar</packaging>

    <name>utilities</name>
    <description>Utilities to solve every actions (folder archiving, old files removal, file within folder checksum calculation asf.)</description>
    <url>https://github.com/pgdro/utilities</url>

    <licenses>
        <license>
            <name>Eclipse Public License - v 2.0</name>
            <url>https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>dgp.eu</id>
            <name>Daniel-Gheorghe Popiniuc</name>
            <email>danielpopiniuc@gmail.com</email>
            <roles>
                <role>Developer</role>
            </roles>
            <timezone>+2</timezone>
            <organization>pgdro</organization>
            <organizationUrl>https://github.com/pgdro</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/pgdro/utilities.git</connection>
        <developerConnection>scm:git:ssh://github.com/pgdro/utilities.git</developerConnection>
        <url>https://github.com/pgdro/utilities</url>
    </scm>

    <properties>
        <!-- File encoding properties -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!-- Build properties -->
        <java.version>27</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <sonar.organization>pgdro</sonar.organization>
        <!-- Dependency versions -->
        <tools.version>2.0.0</tools.version>
        <jackson-databind.version>3.2.3</jackson-databind.version>
        <!-- Build Plugin versions -->
        <central-publishing-maven-plugin.version>0.11.0</central-publishing-maven-plugin.version>
        <depgraph-maven-plugin.version>4.0.5</depgraph-maven-plugin.version>
        <maven-antrun-plugin.version>3.2.0</maven-antrun-plugin.version>
        <maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
        <maven-enforcer-plugin.version>3.6.3</maven-enforcer-plugin.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
        <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
        <maven-pmd-plugin.version>3.28.0</maven-pmd-plugin.version>
        <maven-shade-plugin.version>3.6.2</maven-shade-plugin.version>
        <open-java-format.version>2.98.0.6</open-java-format.version>
        <pmd.version>7.28.0</pmd.version>
        <takari-lifecycle-plugin.version>2.3.4</takari-lifecycle-plugin.version>
        <versions-maven-plugin.version>2.22.0</versions-maven-plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.pgdro</groupId>
            <artifactId>core</artifactId>
            <version>${tools.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Source: https://github.com/ferstl/depgraph-maven-plugin -->
            <!-- Binaries: https://repo1.maven.org/maven2/com/github/ferstl/depgraph-maven-plugin/ -->
            <!-- Description: This Maven plugin generates dependency graphs on single modules or in an aggregated form on multimodule projects. The graphs are represented by .dot files. In case that Graphviz is installed on the machine where this plugin is run, the .dot file can be directly converted into all supported image files. -->
            <plugin>
                <groupId>com.github.ferstl</groupId>
                <artifactId>depgraph-maven-plugin</artifactId>
                <version>${depgraph-maven-plugin.version}</version>
            </plugin>
            <!-- Source: https://github.com/takari/takari-lifecycle/releases -->
            <!-- Binaries: https://repo1.maven.org/maven2/io/takari/maven/plugins/takari-lifecycle-plugin -->
            <!-- Description: Takari Lifecycle Plugin -->
            <plugin>
                <groupId>io.takari.maven.plugins</groupId>
                <artifactId>takari-lifecycle-plugin</artifactId>
                <version>${takari-lifecycle-plugin.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceJar>true</sourceJar>
                    <testJar>false</testJar>
                    <verbose>false</verbose>
                </configuration>
            </plugin>
            <!-- Source: https://maven.apache.org/plugins/maven-antrun-plugin/ -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-antrun-plugin -->
            <!-- Description: Runs Ant scripts embedded in the POM -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven-antrun-plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-pom-as-metadata</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target name="copy-and-rename-pom">
                                <copy file="${basedir}/pom.xml"
                                      tofile="${project.build.outputDirectory}/utilities-pom.xml"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Source: https://maven.apache.org/plugins/maven-checkstyle-plugin/download.cgi -->
            <!-- Source: https://github.com/apache/maven-checkstyle-plugin/ -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin -->
            <!-- Description: Generates a report on violations of code style and optionally fails the build if violations are detected. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven-checkstyle-plugin.version}</version>
                <executions>
                    <execution>
                        <id>check-format</id>
                        <goals>
                            <goal>checkstyle</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>dev.openjavaformat</groupId>
                        <artifactId>open-java-format</artifactId>
                        <version>${open-java-format.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <configLocation>config/checkstyle.xml</configLocation>
                    <consoleOutput>false</consoleOutput>
                    <failsOnError>false</failsOnError>
                    <linkXRef>false</linkXRef>
                </configuration>
            </plugin>
            <!-- Source: https://maven.apache.org/plugins/maven-gpg-plugin/ -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-gpg-plugin -->
            <!-- Description: Signs the project artifacts with GnuPG. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>${maven-gpg-plugin.version}</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                        <configuration>
                            <passphraseEnvName>MAVEN_GPG_PASSPHRASE</passphraseEnvName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Source: https://maven.apache.org/plugins/maven-javadoc-plugin/download.cgi -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin -->
            <!-- Description: The Apache Maven Javadoc Plugin is a plugin that uses the javadoc tool for generating javadocs for the specified project. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <doclint>none</doclint>
                </configuration>
            </plugin>
            <!-- Source: https://github.com/apache/maven-pmd-plugin/ -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-pmd-plugin -->
            <!-- Description: A Maven plugin for the PMD toolkit, that produces a report on both code rule violations and detected copy and paste fragments, as well as being able to fail the build based on these metrics. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${maven-pmd-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-core</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-java</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <rulesets>
                        <ruleset>config/pmd-ruleset.xml</ruleset>
                    </rulesets>
                    <failOnViolation>true</failOnViolation>
                    <linkXRef>false</linkXRef>
                    <printFailingErrors>true</printFailingErrors>
                    <skip>false</skip>
                </configuration>
            </plugin>
            <!-- Website: https://central.sonatype.org/ -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/sonatype/central/central-publishing-maven-plugin/ -->
            <!-- Description: This project is a maven plugin for publishing components in Maven Central, for more details on its usage see https://central.sonatype.org/publish/publish-portal-maven -->
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>${central-publishing-maven-plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                    <autoPublish>true</autoPublish>
                    <waitUntil>published</waitUntil>
                </configuration>
            </plugin>
            <!-- Source: https://github.com/apache/maven-enforcer/tree/enforcer-3.6.3/maven-enforcer-plugin -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/codehaus/mojo/versions-maven-plugin -->
            <!-- Description: The Loving Iron Fist of Maven -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${maven-enforcer-plugin.version}</version>
                <executions>
                    <execution>
                        <id>enforce-java</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>[27,)</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>enforce-maven</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>[3.10,)</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>enforce-no-snapshots</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireReleaseDeps>
                                    <message>No Snapshots Allowed!</message>
                                </requireReleaseDeps>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Source: https://www.mojohaus.org/versions/ -->
            <!-- Binaries: https://repo1.maven.org/maven2/org/codehaus/mojo/versions-maven-plugin -->
            <!-- Description: The Versions Maven Plugin is used when you want to manage the versions of artifacts in a project's POM. -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${versions-maven-plugin.version}</version>
                <configuration>
                    <ignoredVersions type="regex">(?i).*[-_.](alpha|b|beta|rc|cr|milestone|m|ea|preview|snapshot)-?[-_.0-9]*</ignoredVersions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>central</id>
            <url>https://central.sonatype.com/api/v1/publisher</url>
        </repository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>mavenCentral</id>
            <activation>
                <property>
                    <name>release</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>${maven-shade-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>make-fat-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <!-- Keep original JAR -->
                                    <shadedArtifactAttached>true</shadedArtifactAttached>
                                    <transformers>
                                        <!-- add Main-Class to manifest file -->
                                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                            <manifestEntries>
                                                <Main-Class>io.github.pgdro.utilities.cli.ApplicationUtills</Main-Class>
                                                <X-Compile-Source-JDK>${maven.compile.source}</X-Compile-Source-JDK>
                                                <X-Compile-Target-JDK>${maven.compile.target}</X-Compile-Target-JDK>
                                            </manifestEntries>
                                        </transformer>
                                    </transformers>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <property>
                    <name>!release</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>${maven-shade-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>make-fat-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <!-- Keep original JAR -->
                                    <shadedArtifactAttached>true</shadedArtifactAttached>
                                    <!-- Fat JAR classifier -->
                                    <shadedClassifierName>jar-with-dependencies</shadedClassifierName>
                                    <transformers>
                                        <!-- add Main-Class to manifest file -->
                                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                            <manifestEntries>
                                                <Main-Class>io.github.pgdro.utilities.cli.ApplicationUtills</Main-Class>
                                                <X-Compile-Source-JDK>${maven.compile.source}</X-Compile-Source-JDK>
                                                <X-Compile-Target-JDK>${maven.compile.target}</X-Compile-Target-JDK>
                                            </manifestEntries>
                                        </transformer>
                                    </transformers>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
